development:
  adapter: mysql2
  database: devry_development
  encoding: utf8
  collation: utf8_general_ci

test:
  adapter: mysql2
  database: devry_test
  encoding: utf8
  collation: utf8_general_ci